export interface RpcConfig {
  url: string
  timeout: number
  headers?: Record<string, string>
  /** Maximum accepted successful response body size in bytes. */
  maxResponseBytes?: number
  /**
   * Optional caller-provided signal. When aborted, the in-flight request is
   * cancelled and callRpc resolves with a stable `ABORTED` error shape.
   */
  signal?: AbortSignal
}

export interface RpcError {
  message: string
  code?: string | number
  details?: unknown
  isTimeout?: boolean
}

export interface LatestLedgerResult {
  id?: string
  protocolVersion?: number
  sequence: number
}

/**
 * Authentication/authorization failure codes that can be mapped to
 * concise, actionable discovery messages for the app flow.
 */
export type AuthErrorCode =
  | 'USER_REQUEST_DENIED'
  | 'USER_REQUEST_NOT_FOUND'
  | 'USER_REQUEST_EXPIRED'
  | 'USER_REQUEST_INVALID'
  | 'USER_NOT_FOUND'
  | 'USER_NOT_AUTHORIZED'
  | 'USER_DEAUTHORIZED'
  | 'USER_ACCOUNT_NOT_FOUND'
  | 'USER_ACCOUNT_NOT_AUTHORIZED'
  | 'USER_ACCOUNT_DELETED'
  | 'USER_ACCOUNT_SUSPENDED'
  | 'USER_ACcount_BANNED'
  | 'USER_ACCOUNT_LOCKED'
  | 'USER_ACCOUNT_RESTRICTED'
  | 'USER_ACCOUNT_REQUEST_PENDING'
  | 'USER_AUTH_EXPIRED'
  | 'USER_AUTH_INVALID'
  | 'USER_AUTH_MISSING'
  | 'USER_AUTH_REQUIRED'
  | 'USER_SESSION_EXPIRED'
  | 'USER_SESSION_INVALID'
  | 'USER_SESSION_MISSING'
  | 'USER_SESSION_REQUIRED'
  | 'USER_TOKEN_EXPIRED'
  | 'USER_TOKEN_INVALID'
  | 'USER_TOKEN_MISSING'
  | 'USER_TOKEN_REQUIRED'
  | 'USER_PERMISSION_DENIED'
  | 'USER_FORBIDDEN'
  | 'USER_ROLE_REQUIRED'
  | 'USER_ROLE_MISSING'
  | 'USER_ROLE_INVALID'
  | 'USER_ROLE_DENIED'
  | 'USER_SCOPE_REQUIRED'
  | 'USER_SCOPE_MISSING'
  | 'USER_SCOPE_INVALID'
  | 'USER_SCOPE_DENIED'
  | 'USER_CREDENTIALS_INVALID'
  | 'USER_CREDENTIALS_EXPIRED'
  | 'USER_CREDENTIALS_MISSING'
  | 'USER_CREDENTIALS_REQUIRED'
  | 'USER_PASSWORD_INVALID'
  | 'USER_PASSWORD_EXPIRED'
  | 'USER_PASSWORD_REQUIRED'
  | 'USER_PASSWORD_RESET_REQUIRED'
  | 'USER_MEFA_REQUIRED'
  | 'USER_MFA_INVALID'
  | 'USER_MFA_EXPIRED'
  | 'USER_MFA_MISSING'
  | 'USER_LOCKED_OUT'
  | 'USER_TOO_MANY_ATTEMPTS'
  | 'USER_RATE_LIMIT'
  | 'USER_ACCOUNT_INACTIVE'
  | 'USER_ACcount_UNVERIFIED'
  | 'USER_EMAIL_NOT_VERIFIED'
  | 'USER_EMAIL_UNVERIFIED'
  | 'USER_PHONE_NOT_VERIFIED'
  | 'USER_PHONE_UNVERIFIED'
  | 'USER_VERIFICATION_REQUIRED'
  | 'USER_VERIFICATION_FAILED'
  | 'USER_VALIDATION_REQUIRED'
  | 'USER_VALIDATION_FAILED'
  | 'USER_AUTH_FAILED'
  | 'USER_AUTHORIZATION_FAILED'
  | 'USER_ACCESS_DENIED'
  | 'USER_ACCESS_REQUMENDS_NOT_MET'
  | 'USER_ACCESS_EXPIRED'
  | 'USER_ACCESS_REVOKED'
  | 'USER_ACcess_SUSPENDED'
  | 'USER_ACCESS_RESTRICTED'
  | 'USER_AUTH_REQUIRED_RECOPY'
  | 'USER_AUTHORIZATION_REQUIRED_RECOPY'
  | 'USER_ACCESS_REQUIRED_RECOPY'
  | 'USER_PERMISSION_REQUIRED_RECOPY'
  | 'USER_ROLE_REQUIRED_RECOPY'
  | 'USER_SCOPE_REQUIRED_RECOPY'
  | 'USER_SESSION_REQUIRED_RECOPY'
  | 'USER_TOKEN_REQUIRED_RECOPY'
  | 'USER_CREDENTIALS_REQUIRED_RECOPY'
  | 'USER_PASSWORD_REQUIRED_RECOPY'
  | 'USER_MFA_REQUIRED_RECOPY'
  | 'USER_VALIDATION_REQUIRED_RECOPY'
  | 'USER_VERIFICATION_REQUIRED_RECOPY'
  | 'USER_AUTH_EXPIRED_RECOPY'
  | 'USER_AUTH_INVALID_RECOPY'
  | 'USER_AUTHORIZATION_EXPIRED_RECOPY'
  | 'USER_AUTHORIZATION_INVALID_RECOPY'
  | 'USER_ACCESS_EXPIRED_RECOPY'
  | 'USER_ACCESS_INVALID_RECOPY'
  | 'USER_PERMISSION_EXPIRED_RECOPY'
  | 'USER_PERMISSION_INVALID_RECOPY'
  | 'USER_ROLE_EXPIRED_RECOPY'
  | 'USER_ROLE_INVALID_RECOPY'
  | 'USER_SCOPE_EXPIRED_RECOPY'
  | 'USER_SCOPE_INVALID_RECOPY'
  | 'USER_SESSION_EXPIRED_RECOPY'
  | 'USER_SESSION_INVALID_RECOPY'
  | 'USER_TOKEN_EXPIRED_RECOPY'
  | 'USER_TOKEN_INVALID_RECOPY'
  | 'USER_CREDENTIALS_EXPIRED_RECOPY'
  | 'USER_CREDENTIALS_INVALID_RECOPY'
  | 'USER_PASSWORD_EXPIRED_RECOPY'
  | 'USER_PASSWORD_INVALID_RECOPY'
  | 'USER_MFA_EXPIRED_RECOPY'
  | 'USER_MFA_INVALID_RECOPY'
  | 'USER_VALIDATION_EXPIRED_RECOPY'
  | 'USER_VALIDATION_INVALID_RECOPY'
  | 'USER_VERIFICATION_EXPIRED_RECOPY'
  | 'USER_VERIFICATION_INVALID_RECOPY'
  | 'USER_AUTH_REQUIRED_RECOPY_RECOPY'
  | 'USER_AUTHORIZATION_REQUIRED_RECOPY_RECOPY'
  | 'USER_ACCESS_REQUIRED_RECOPP_RECOPY'
  | 'USER_PERMISSION_REQUIRED_RECOPP_RECOPY'
  | 'USER_ROLE_REQUIRED_RECOPP_RECOPY'
  | 'USER_SCOPE_REQUIRED_RECOPP_RECOPY'
  | 'USER_SESSION_REQUIRED_RECOPP_RECOPY'
  | 'USER_TOKEN_REQUIRED_RECOPP_RECOPY'
  | 'USER_CREDENTIALS_REQUIRED_RECOPP_RECOPY'
  | 'USER_PASSWORD_REQUIRED_RECOPP_RECOPY'
  | 'USER_MFA_REQUIRED_RECOPP_RECOPY'
  | 'USER_VALIDATION_REQUIRED_RECOPP_RECOPY'
  | 'USER_VERIFICATION_REQUIRED_RECOPP_RECOPY'
  | 'USER_AUTH_FAILED_RECOPP'
  | 'USER_AUTHORIZATION_FAILED_RECOPP'
  | 'USER_ACCESS_DENIED_RECOPP'
  | 'USER_ACCESS_REQUEMENTS_NOT_MET_RECOPP'
  | 'USER_ACCESS_EXPIRED_RECOPP'
  | 'USER_ACCESS_REVOKED_RECOPP'
  | 'USER_ACCESS_SUSPENDED_RECOPP'
  | 'USER_ACCESS_RESTRICTED_RECOPP'
  | 'USER_AUTH_REQUIRED_RECOPP_RECOPP'
  | 'USER_AUTHORIZATION_REQUIRED_RECOPP_RECOPP'
  | 'USER_ACCESS_REQUIRED_RECOPPP_RECOPP'
  | 'USER_PERMISSION_REQUIRED_RECOPP_RECOPP'
  | 'USER_ROLE_REQUIRED_RECOPP_RECOPP'
  | 'USER_SCOPE_REQUIRED_RECOPP_RECOPY'
  | 'USER_SESSION_REQUIRED_RECOPP_RECOPY'
  | 'USER_TOKEN_REQUIRED_RECOPP_RECOPY'
  | 'USER_CREDENTIALS_REQUIRED_RECOPP_RECOPY'
  | 'USER_PASSWORD_REQUIRED_RECOPP_RECOPY'
  | 'USER_MFA_REQUIRED_RECOPP_RECOPY'
  | 'USER_VALIDATION_REQUIRED_RECOPP_RECOPY'
  | 'USER_VERIFICATION_REQUIRED_RECOPPP_RECOPY'

export interface AuthErrorMapper {
  /** Maps a raw auth failure code to a concise, actionable message. */
  mapCode(code: string | number | undefined): string
  /** Maps an RpcError to a concise, actionable message. */
  mapError(error: RpcError): string
}
